-- PEF Monitor 초기 저장 스키마
-- Supabase Dashboard > SQL Editor에서 실행

create table if not exists public.disclosures (
  id bigint generated by default as identity primary key,

  rcept_no text not null unique,
  corp_code text,
  corp_name text not null,
  report_nm text not null,
  filer_name text,
  receipt_date date not null,

  dart_url text,
  event_type text,
  importance smallint check (importance between 1 and 5),
  why_watch text,

  related_companies jsonb not null default '[]'::jsonb,
  related_disclosures jsonb not null default '[]'::jsonb,
  raw_data jsonb not null default '{}'::jsonb,

  first_seen_at timestamptz not null default now(),
  last_updated_at timestamptz not null default now()
);

create index if not exists disclosures_receipt_date_idx
on public.disclosures (receipt_date desc);

create index if not exists disclosures_corp_name_idx
on public.disclosures (corp_name);

create index if not exists disclosures_event_type_idx
on public.disclosures (event_type);

create table if not exists public.monitor_runs (
  id bigint generated by default as identity primary key,

  source text not null default 'dart',
  status text not null,
  fetched_count integer not null default 0,
  saved_count integer not null default 0,
  error_message text,

  started_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.disclosures enable row level security;
alter table public.monitor_runs enable row level security;

-- 기사 후보: 공시 원문(raw_data)과 분리해 점수·취재 질문을 바로 조회한다.
create table if not exists public.article_candidates (
  rcept_no text primary key references public.disclosures(rcept_no) on delete cascade,
  corp_code text,
  corp_name text not null,
  event_id text not null,
  event_type text not null,
  deal_stage text,
  story_score smallint not null check (story_score between 0 and 100),
  story_bucket text not null check (story_bucket in ('story', 'verify', 'archive')),
  headline text,
  change_summary text,
  why_story text,
  key_numbers jsonb not null default '[]'::jsonb,
  call_targets jsonb not null default '[]'::jsonb,
  reporter_questions jsonb not null default '[]'::jsonb,
  article_angles jsonb not null default '[]'::jsonb,
  score_breakdown jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  workflow_status text not null default 'new',
  reporter_note text,
  first_seen_at timestamptz not null default now(),
  last_updated_at timestamptz not null default now()
);

create index if not exists article_candidates_priority_idx
on public.article_candidates (story_bucket, story_score desc, last_updated_at desc);

create index if not exists article_candidates_corp_idx
on public.article_candidates (corp_code, last_updated_at desc);

-- 기업·운용사·SPC를 하나의 개체로 관리한다.
create table if not exists public.entities (
  id uuid primary key default gen_random_uuid(),
  entity_key text,
  canonical_name text not null,
  entity_type text not null default 'company',
  dart_corp_code text,
  stock_code text,
  aliases jsonb not null default '[]'::jsonb,
  watch_priority smallint not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.entities add column if not exists entity_key text;

create unique index if not exists entities_entity_key_uidx
on public.entities (entity_key);

create unique index if not exists entities_dart_corp_code_uidx
on public.entities (dart_corp_code) where dart_corp_code is not null;

create index if not exists entities_name_idx
on public.entities (canonical_name);

-- 하나의 거래에 여러 공시·뉴스·관계자를 묶는다.
create table if not exists public.deals (
  id uuid primary key default gen_random_uuid(),
  deal_key text not null unique,
  deal_name text not null,
  deal_type text,
  current_stage text,
  status text not null default 'watching',
  target_entity_id uuid references public.entities(id),
  estimated_value numeric,
  currency text not null default 'KRW',
  summary text,
  source_signal_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.deals add column if not exists source_signal_id text;

create index if not exists deals_source_signal_idx
on public.deals (source_signal_id);

create table if not exists public.deal_events (
  id bigint generated by default as identity primary key,
  event_key text,
  deal_id uuid references public.deals(id) on delete cascade,
  source_signal_id text,
  rcept_no text references public.disclosures(rcept_no) on delete set null,
  event_date date not null,
  event_type text not null,
  stage_before text,
  stage_after text,
  headline text,
  facts jsonb not null default '[]'::jsonb,
  changes jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  confidence smallint not null default 3 check (confidence between 1 and 5),
  created_at timestamptz not null default now()
);

alter table public.deal_events add column if not exists event_key text;
alter table public.deal_events add column if not exists source_signal_id text;

create unique index if not exists deal_events_event_key_uidx
on public.deal_events (event_key);

create index if not exists deal_events_timeline_idx
on public.deal_events (deal_id, event_date desc);

create table if not exists public.entity_relations (
  id bigint generated by default as identity primary key,
  relation_key text,
  from_entity_id uuid not null references public.entities(id) on delete cascade,
  to_entity_id uuid not null references public.entities(id) on delete cascade,
  relation_type text not null,
  deal_id uuid references public.deals(id) on delete set null,
  basis text,
  confidence smallint not null default 3 check (confidence between 1 and 5),
  valid_from date,
  valid_to date,
  source_rcept_no text references public.disclosures(rcept_no) on delete set null,
  source_signal_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.entity_relations add column if not exists relation_key text;
alter table public.entity_relations add column if not exists source_signal_id text;

create unique index if not exists entity_relations_relation_key_uidx
on public.entity_relations (relation_key);

create index if not exists entity_relations_from_idx on public.entity_relations (from_entity_id);
create index if not exists entity_relations_to_idx on public.entity_relations (to_entity_id);

-- 기사·보도자료·공시의 출처와 검증 가능한 사실을 분리한다.
create table if not exists public.source_documents (
  id uuid primary key default gen_random_uuid(),
  source_key text,
  source_type text not null,
  source_name text,
  title text not null,
  source_url text,
  published_at timestamptz,
  excerpt text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.source_documents add column if not exists source_key text;

create unique index if not exists source_documents_source_key_uidx
on public.source_documents (source_key);

create table if not exists public.fact_claims (
  id bigint generated by default as identity primary key,
  claim_key text,
  subject_entity_id uuid references public.entities(id) on delete cascade,
  deal_id uuid references public.deals(id) on delete cascade,
  predicate text not null,
  value jsonb not null,
  source_document_id uuid references public.source_documents(id) on delete set null,
  source_rcept_no text references public.disclosures(rcept_no) on delete set null,
  source_signal_id text,
  verification_status text not null default 'unverified',
  valid_from date,
  valid_to date,
  created_at timestamptz not null default now()
);

alter table public.fact_claims add column if not exists claim_key text;
alter table public.fact_claims add column if not exists source_signal_id text;

create unique index if not exists fact_claims_claim_key_uidx
on public.fact_claims (claim_key);

create index if not exists fact_claims_subject_idx
on public.fact_claims (subject_entity_id, predicate);

-- 공시별 국내뉴스·외신·보도자료. 원문 전체가 아니라 제목·링크·짧은 설명만 저장한다.
create table if not exists public.related_sources (
  id bigint generated by default as identity primary key,
  rcept_no text not null references public.disclosures(rcept_no) on delete cascade,
  corp_code text,
  corp_name text not null,
  category text not null check (category in ('domestic', 'foreign', 'press_release')),
  source_name text,
  title text not null,
  source_url text not null,
  published_at timestamptz,
  snippet text,
  language text,
  provider text,
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (rcept_no, source_url)
);

create index if not exists related_sources_candidate_idx
on public.related_sources (rcept_no, category, published_at desc);

create index if not exists related_sources_company_idx
on public.related_sources (corp_code, published_at desc);

alter table public.article_candidates enable row level security;
alter table public.entities enable row level security;
alter table public.deals enable row level security;
alter table public.deal_events enable row level security;
alter table public.entity_relations enable row level security;
alter table public.source_documents enable row level security;
alter table public.fact_claims enable row level security;
alter table public.related_sources enable row level security;

-- 공시·뉴스·보도자료·출자공고를 같은 형식으로 쌓는 취재단서 수집함.
create table if not exists public.reporting_leads (
  signal_id text primary key,
  collected_at timestamptz not null default now(),
  occurred_at timestamptz,
  source_type text not null,
  source_name text,
  title text not null,
  source_url text not null,
  target_id text,
  target_name text,
  target_category text,
  event_type text not null default 'general',
  key_numbers jsonb not null default '[]'::jsonb,
  key_dates jsonb not null default '[]'::jsonb,
  interpretation text,
  checkpoints jsonb not null default '[]'::jsonb,
  story_score smallint not null default 0 check (story_score between 0 and 100),
  alert_grade text not null default 'P4' check (alert_grade in ('P1', 'P2', 'P3', 'P4')),
  verification_status text not null default 'unverified',
  story_candidate text not null default 'hold',
  workflow_status text not null default 'new',
  related_company_ids jsonb not null default '[]'::jsonb,
  related_person_ids jsonb not null default '[]'::jsonb,
  related_fund_ids jsonb not null default '[]'::jsonb,
  related_deal_ids jsonb not null default '[]'::jsonb,
  dedupe_key text not null,
  raw_data jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists reporting_leads_priority_idx
on public.reporting_leads (alert_grade, story_score desc, occurred_at desc);

create index if not exists reporting_leads_target_idx
on public.reporting_leads (target_id, occurred_at desc);

create index if not exists reporting_leads_event_idx
on public.reporting_leads (event_type, occurred_at desc);

create unique index if not exists reporting_leads_dedupe_uidx
on public.reporting_leads (dedupe_key);

-- 매일·매주 브리핑 결과를 보관할 자리. 자동 생성 API는 다음 단계에서 이 표를 사용한다.
create table if not exists public.briefings (
  id uuid primary key default gen_random_uuid(),
  briefing_type text not null check (briefing_type in ('daily', 'weekly')),
  period_start date not null,
  period_end date not null,
  title text not null,
  summary text,
  lead_ids jsonb not null default '[]'::jsonb,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (briefing_type, period_start, period_end)
);

alter table public.reporting_leads enable row level security;
alter table public.briefings enable row level security;
