-- PEF Monitor 초기 저장 스키마
-- Supabase Dashboard > SQL Editor에서 실행

create table if not exists public.disclosures (
  id bigint generated by default as identity primary key,

  rcept_no text not null unique,
  corp_code text,
  corp_name text not null,
  report_nm text not null,
  filer_name text,
  receipt_date date not null,

  dart_url text,
  event_type text,
  importance smallint check (importance between 1 and 5),
  why_watch text,

  related_companies jsonb not null default '[]'::jsonb,
  related_disclosures jsonb not null default '[]'::jsonb,
  raw_data jsonb not null default '{}'::jsonb,

  first_seen_at timestamptz not null default now(),
  last_updated_at timestamptz not null default now()
);

create index if not exists disclosures_receipt_date_idx
on public.disclosures (receipt_date desc);

create index if not exists disclosures_corp_name_idx
on public.disclosures (corp_name);

create index if not exists disclosures_event_type_idx
on public.disclosures (event_type);

create table if not exists public.monitor_runs (
  id bigint generated by default as identity primary key,

  source text not null default 'dart',
  status text not null,
  fetched_count integer not null default 0,
  saved_count integer not null default 0,
  error_message text,

  started_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.disclosures enable row level security;
alter table public.monitor_runs enable row level security;
