(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.IBDartDesk=api;api.init();}})(typeof window==='object'?window:globalThis,function(){
'use strict';
const STORE='ib_dart_reviews_v1',PROJECTS='pef_my_reporting_projects_v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const receipt=n=>/^\d{14}$/.test(String(n||''));
const url=n=>receipt(n)?'https://dart.fss.or.kr/dsaf001/main.do?rcpNo='+n:'#';
const date=v=>/^\d{8}$/.test(String(v||''))?`${v.slice(0,4)}.${v.slice(4,6)}.${v.slice(6,8)}`:'일자 미확인';
const correction=x=>/^\s*(?:\[(?:기재정정|첨부정정|정정)\]|기재정정|첨부정정|정정)/.test(x.report_nm||'');
const concern=x=>/철회|중단|취소|회생|부도|연체|횡령|배임|감사의견거절|감사의견부적정/.test(x.report_nm||'');
function base(v){return String(v||'').replace(/^\s*(?:\[(?:기재정정|첨부정정|정정)\]|기재정정|첨부정정|정정)\s*/,'').replace(/\s+/g,' ').trim();}
function buildGroups(items){const m=new Map();for(const x of items||[]){if(!receipt(x.rcept_no))continue;const key=[x.corp_code||x.corp_name,base(x.report_nm),x.flr_nm||x.rcept_no].join('|');if(!m.has(key))m.set(key,[]);if(!m.get(key).some(a=>a.rcept_no===x.rcept_no))m.get(key).push(x);}return [...m.values()].map(rows=>{rows.sort((a,b)=>b.rcept_no.localeCompare(a.rcept_no));return{latest:rows[0],items:rows};});}
function mergeProject(rows,item,review){if(!Array.isArray(rows))throw Error('취재 목록 형식을 확인해야 합니다.');const pid='project-dart-'+item.rcept_no,now=new Date().toISOString(),out=rows.map(p=>({...p}));let p=out.find(p=>p.project_id===pid);
  if(!p){const changes=review?.changes||[],qs=review?.questions||[];p={project_id:pid,clue_id:'dart-'+item.rcept_no,title:item.corp_name+' · '+base(item.report_nm),status:'추가확인',notes:'',judgment:null,judgment_history:[],created_at:now,
    clue:{clue_id:'dart-'+item.rcept_no,detector:'dart_manual_review',fact_status:'단서',headline:item.corp_name+' · '+base(item.report_nm),one_line_signal:changes.length?'정정표에서 변경값을 추출했습니다. 원문 검수와 변경 사유 확인이 필요합니다.':'DART 원문에서 거래 조건과 후속 이행 여부를 확인할 취재입니다.',previous_state:'동일 공시의 정정 전 항목을 기준으로 대조합니다. 서로 다른 거래의 과거 공시를 임의 연결하지 않습니다.',changed_fact:changes.length?changes.slice(0,4).map(d=>`${d.label}: ${d.before} → ${d.after}`).join(' / '):'현재 원문만으로 실질 변경 여부 미확인',confirmed_facts:[],reported:[],unknowns:qs.map(q=>q.still_needed),questions:qs.map(q=>q.question),hypothesis:'공시상 조건 변경이 실제 계약 이행이나 자금조달에 영향을 주었는지 확인한다.',falsification:'기재오류 정정이거나 실제 계약·이행 조건에 변동이 없다면 실질 영향 가설을 재검토한다.',sources:[{source_id:'dart:'+item.rcept_no,label:item.report_nm,url:url(item.rcept_no)}],next_action:'변경 사유와 실제 이행 여부를 공시 담당자·거래상대방에게 확인'}};out.unshift(p);}
  p.dart_review_receipts=[...new Set([...(p.dart_review_receipts||[]),item.rcept_no])];p.updated_at=now;return{rows:out,id:pid};
}
function evidenceHtml(r){if(!r?.ok)return '<p class="dd-empty">원문을 읽지 못했습니다. 공시 원문에서 확인해주세요.</p>';
  const rows=r.changes||[],fields=r.current_fields||[];
  return `<p class="dd-note">${esc(r.comparison_note)}</p>${rows.length?`<div class="dd-changes">${rows.map(d=>`<article class="dd-change" id="dd-e-${esc(d.evidence_id)}"><b>${esc(d.label)}</b><div class="dd-before-after"><div><small>정정 전</small><span>${esc(d.before)}</span></div><span class="dd-arrow" aria-hidden="true">→</span><div><small>정정 후</small><strong>${esc(d.after)}</strong></div></div>${d.day_delta!==null?`<p class="dd-days">기재된 날짜 기준 ${Math.abs(d.day_delta)}일 ${d.day_delta>0?'뒤로':'앞으로'} 변경 · 실제 이행은 미확인</p>`:''}${d.reason?`<p><small>공시의 정정 사유</small> ${esc(d.reason)}</p>`:''}<a href="${url(r.rcept_no)}" target="_blank" rel="noopener noreferrer">원문 ↗</a><small class="dd-location">${esc(d.source.location)} · 자동 추출, 검수 전</small></article>`).join('')}</div>`:'<p class="dd-empty">비교 가능한 변경값을 추출하지 못했습니다. 변경이 없다는 뜻은 아닙니다.</p>'}
  ${fields.length?`<details class="dd-details"><summary>현재 원문에서 읽은 조건 ${fields.length}개</summary><dl class="dd-fields">${fields.map(f=>`<div id="dd-e-${esc(f.evidence_id)}"><dt>${esc(f.raw_label)}</dt><dd>${esc(f.value)}<small>${esc(f.source.location)}</small></dd></div>`).join('')}</dl></details>`:''}
  <h4>다음 취재 질문</h4><div class="dd-questions">${(r.questions||[]).map(q=>`<div><b>${esc(q.title)}</b><p>${esc(q.question)}</p><small>${esc(q.still_needed)}</small><div>${q.evidence_ids.map((e,i)=>`<a href="#dd-e-${esc(e)}">근거 ${i+1} 보기</a>`).join(' · ')}</div></div>`).join('')}</div>
  ${r.warnings?.length?`<details class="dd-details"><summary>자동 추출에서 제외한 항목·한계</summary><p>${r.warnings.map(esc).join('<br>')}</p></details>`:''}`;
}
function brief(item,r){return[item.corp_name+' · '+item.report_nm,url(item.rcept_no),'DART 원문 자동 추출 · 검수 전',(r?.changes||[]).map(d=>`${d.label}: ${d.before} → ${d.after}\n공시의 정정 사유: ${d.reason||'정정표에서 별도 사유 미확보'}\n${d.source.location}`).join('\n'),...(r?.questions||[]).map(q=>'질문: '+q.question+'\n남은 확인: '+q.still_needed),...(r?.warnings||[])].filter(Boolean).join('\n\n');}
function init(){if(typeof document==='undefined')return;const $=s=>document.querySelector(s),read=(k,def)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v===null?def:v;}catch(_){return def;}};
  function attachProjects(){const rows=read(PROJECTS,[]),reviews=read(STORE,{});if(!Array.isArray(rows))return;
    const targets=[...document.querySelectorAll('.project-card')].map(el=>({el,p:rows.find(p=>p.project_id===el.dataset.id)}));const judge=$('#judgeRoot .judge-panel');if(judge){const pid=new URLSearchParams(location.search).get('project')||localStorage.getItem('pef_selected_project_v1');targets.push({el:judge,p:rows.find(p=>p.project_id===pid)});}
    for(const{el,p}of targets){if(!p?.dart_review_receipts?.length||el.querySelector('.dd-linked'))continue;const d=document.createElement('details');d.className='dd-linked dd-details';d.innerHTML='<summary>DART 변경값·원문·질문 보기</summary><p class="dd-note">공개자료 자동 추출입니다. 기존 취재 메모와 기사화 판단을 바꾸지 않습니다.</p>'+p.dart_review_receipts.filter(n=>reviews[n]?.ok).map(n=>evidenceHtml(reviews[n])).join('');el.append(d);}
  }
  if(!$('#dartDesk')){let scheduled=false;new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;attachProjects();});}).observe(document.body,{childList:true,subtree:true});attachProjects();return;}
  let items=[],groups=[],reviews=read(STORE,{}),days=3,filter='all',group='ALL',query='',view='desk',shown=60,open=new Set(),loading=new Set(),failed=new Map(),sequence=0,controller,batching=false;
  if(!reviews||typeof reviews!=='object'||Array.isArray(reviews))reviews={};
  const message=t=>{$('#deskMessage').textContent=t;};
  function matches(g){const x=g.latest,r=reviews[x.rcept_no],q=query.toLowerCase().trim();return(group==='ALL'||x.group_id===group)&&(!q||g.items.some(a=>[a.corp_name,a.flr_nm,a.report_nm].join(' ').toLowerCase().includes(q)))&&(filter==='all'||filter==='correction'&&g.items.some(correction)||filter==='concern'&&g.items.some(concern)||filter==='changed'&&r?.changes?.length||filter==='unread'&&!r?.ok);}
  function mini(x){const r=reviews[x.rcept_no];if(r?.changes?.length)return `<div class="dd-delta-preview">${r.changes.slice(0,2).map(d=>`<div><b>${esc(d.label)}</b><span>${esc(d.before)} <em>→</em> <strong>${esc(d.after)}</strong></span></div>`).join('')}<small>현재 공시의 정정표 · 자동 추출, 검수 전${r.changes.length>2?' · 전체 '+r.changes.length+'행':''}</small></div>`;
    if(r?.ok)return '<p class="dd-note">원문 열람 · 비교 가능한 변경값 미확보. 상세에서 현재 조건과 질문을 확인하세요.</p>';
    const label=concern(x)?'철회·중단·위험 관련 제목':correction(x)?'정정공시 · 변경내용 미검토':'새 공시 · 원문 미검토';return `<p class="dd-signal">${label}</p><p class="dd-next">${esc(x.next_check||'금액·상대방·일정·실제 이행 여부 확인')}</p>`;
  }
  function panel(x){const r=reviews[x.rcept_no];return `<section class="dd-review" aria-label="원문 검토 결과">${loading.has(x.rcept_no)?'<p role="status">공시 원문의 정정표와 조건을 읽는 중입니다…</p>':r?.ok?evidenceHtml(r):`<p class="dd-empty">${esc(failed.get(x.rcept_no)||'원문 자동 검토를 시작해주세요.')}</p>`}<div class="dd-review-actions"><button data-read="${x.rcept_no}">다시 읽기</button>${r?.ok?`<button data-project="${x.rcept_no}" class="dd-primary">진행중 취재로 보내기 →</button><button data-copy="${x.rcept_no}">질문·근거 복사</button>`:''}</div></section>`;}
  function card(g){const x=g.latest,n=x.rcept_no;return `<article class="dd-card ${reviews[n]?.changes?.length?'has-change':''}"><div class="dd-card-head"><span class="dd-category">${esc(x.group_label||'공시')}</span><time>${date(x.rcept_dt)}</time><a href="${url(n)}" target="_blank" rel="noopener noreferrer">DART 원문 ↗</a></div><h3>${esc(x.corp_name)}</h3><div class="dd-report-title">${esc(x.report_nm)}</div><div class="dd-filer">제출자 ${esc(x.flr_nm||'미확인')}</div>${mini(x)}<div class="dd-card-actions"><button class="dd-primary" data-open="${n}" ${loading.has(n)?'disabled':''}>${loading.has(n)?'원문 읽는 중…':open.has(n)?'검토 결과 접기':reviews[n]?.ok?'변경값·질문 보기':'원문·변경내용 읽기'}</button>${g.items.length>1?`<details class="dd-siblings" ${g.items.slice(1).some(a=>open.has(a.rcept_no))?'open':''}><summary>같은 공시명 ${g.items.length}건</summary><p>회사·공시명·제출자 기준 검색 묶음입니다. 동일 거래로 확인한 이력이 아닙니다.</p>${g.items.map(a=>`<div><a href="${url(a.rcept_no)}" target="_blank" rel="noopener noreferrer">${date(a.rcept_dt)} · ${esc(a.report_nm)}</a><button data-read="${a.rcept_no}">이 원문 읽기</button>${a.rcept_no!==n&&open.has(a.rcept_no)?panel(a):''}</div>`).join('')}</details>`:''}</div>${open.has(n)?panel(x):''}</article>`;}
  function render(){const list=groups.filter(matches).sort((a,b)=>Number(Boolean(reviews[b.latest.rcept_no]?.changes?.length))-Number(Boolean(reviews[a.latest.rcept_no]?.changes?.length))||b.latest.rcept_no.localeCompare(a.latest.rcept_no));$('#dartCards').innerHTML=list.length?list.slice(0,shown).map(card).join(''):'<p class="dd-empty">조건에 맞는 공시가 없습니다. 다른 필터나 조회 기간을 선택해주세요.</p>';$('#more').hidden=list.length<=shown;
    $('#sReview').textContent=items.filter(x=>reviews[x.rcept_no]?.ok).length;$('#sDiff').textContent=items.filter(x=>reviews[x.rcept_no]?.changes?.length).length;$('#sTotal').textContent=items.length;
    $('#deskCount').textContent=`${list.length}개 공시명 묶음 · 변경값 확보 건 먼저, 나머지 최신순`;
    const raw=items.filter(x=>matches({latest:x,items:[x]}));$('#rawRows').innerHTML=raw.map(x=>`<tr><td>${date(x.rcept_dt)}</td><td>${esc(x.corp_name)}</td><td><a href="${url(x.rcept_no)}" target="_blank" rel="noopener noreferrer">${esc(x.report_nm)}</a></td><td>${esc(x.flr_nm)}</td><td><button data-read="${x.rcept_no}">원문 읽기</button></td></tr>`).join('');
    $('#deskView').hidden=view!=='desk';$('#rawView').hidden=view!=='raw';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===view));document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('on',b.dataset.filter===filter));
  }
  async function readReceipt(n,{expand=true}={}){if(!receipt(n)||loading.has(n))return;loading.add(n);if(expand)open.add(n);failed.delete(n);render();
    try{const r=await fetch('/api/dart-feed?action=review&rcept_no='+n,{cache:'no-store',signal:AbortSignal.timeout(25000)}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'원문 읽기 실패');reviews[n]=d;try{localStorage.setItem(STORE,JSON.stringify(reviews));}catch(_){message('브라우저 저장공간이 부족합니다. 이번 결과를 복사해 보관해주세요. 기존 기록은 지우지 않았습니다.');}}
    catch(e){failed.set(n,e.name==='TimeoutError'?'원문 응답이 늦습니다. 원문 링크에서 확인하거나 다시 읽기를 눌러주세요.':e.message);}finally{loading.delete(n);render();}
  }
  async function batch(){if(batching)return;batching=true;$('#batch').disabled=true;const list=groups.filter(matches).map(g=>g.latest).filter(x=>correction(x)&&!reviews[x.rcept_no]?.ok&&!failed.has(x.rcept_no)).slice(0,3);if(!list.length)message('현재 목록에서 새로 읽을 정정공시가 없습니다. 개별 공시의 다시 읽기를 이용하세요.');for(let i=0;i<list.length;i++){message(`정정공시 원문 ${i+1}/${list.length}건 확인 중…`);await readReceipt(list[i].rcept_no,{expand:false});}if(list.length)message(`정정공시 ${list.length}건 조회를 마쳤습니다. 변경값과 미확보 항목을 확인하세요.`);batching=false;$('#batch').disabled=false;}
  async function load(fresh=false){controller?.abort();controller=new AbortController();const token=++sequence;$('#refresh').disabled=true;$('#status').textContent='DART 확인 중…';
    try{const r=await fetch(`/api/dart-feed?days=${days}&limit=700${fresh?'&fresh=1':''}&_=${Date.now()}`,{signal:controller.signal,cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'조회 실패');if(token!==sequence)return;items=d.items||[];groups=buildGroups(items);shown=60;const cov=d.coverage||{};$('#coverage').textContent=`${d.range?.bgn||''}~${d.range?.end||''} · 수집 ${d.scanned||0}건 중 관련 공시 ${d.matched??items.length}건${cov.complete===false?' · 일부 페이지 미수집':''}${cov.display_limited?' · 표시 한도 적용':''} · 조회 ${new Date(d.fetched_at||Date.now()).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul'})}`;$('#coverage').classList.toggle('dd-warning',cov.complete===false);$('#status').textContent=`${days}일 · 관련 공시 ${items.length}건`;render();}
    catch(e){if(token!==sequence||e.name==='AbortError')return;message('조회 실패: '+e.message+(items.length?' 이전 목록을 유지합니다.':''));$('#status').textContent='조회 실패';}finally{if(token===sequence)$('#refresh').disabled=false;}
  }
  $('#refresh').onclick=()=>load(true);$('#batch').onclick=batch;$('#more').onclick=()=>{shown+=60;render();};$('#search').oninput=e=>{query=e.target.value;shown=60;render();};$('#groups').onchange=e=>{group=e.target.value;render();};
  document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.days){days=Number(b.dataset.days);document.querySelectorAll('[data-days]').forEach(x=>x.classList.toggle('on',x===b));load(true);}
    if(b.dataset.filter){filter=b.dataset.filter;shown=60;render();}if(b.dataset.view){view=b.dataset.view;render();}
    const n=b.dataset.open||b.dataset.read;if(n){if(b.dataset.open&&open.has(n)){open.delete(n);render();}else if(reviews[n]?.ok&&!b.dataset.read){open.add(n);render();}else{view='desk';await readReceipt(n);}}
    if(b.dataset.project){const n=b.dataset.project,x=items.find(x=>x.rcept_no===n);if(!x)return;try{const result=mergeProject(read(PROJECTS,[]),x,reviews[n]);localStorage.setItem(PROJECTS,JSON.stringify(result.rows));location.href='/projects.html?project='+encodeURIComponent(result.id);}catch(err){message('저장하지 못했습니다: '+err.message);}}
    if(b.dataset.copy){const n=b.dataset.copy,x=items.find(x=>x.rcept_no===n);if(!x)return;const content=brief(x,reviews[n]);try{await navigator.clipboard.writeText(content);message('질문·변경값·출처를 복사했습니다.');}catch(_){const t=document.createElement('textarea');t.className='dd-copy';t.value=content;t.readOnly=true;b.parentElement.append(t);t.focus();t.select();}}
  });load().then(()=>batch());
}
return{buildGroups,mergeProject,correction,concern,base,evidenceHtml,brief,init};
});