(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./dart-reporting-topics'):root.IBDartTopics);if(typeof module==='object'&&module.exports)module.exports=api;else{root.IBDartDesk=api;api.init();}})(typeof window==='object'?window:globalThis,function(Topics){
'use strict';
// Public DART receipt IDs are the only data sent to the API. Reporting notes stay in this browser.
const STORE='ib_dart_reviews_v1',PROJECTS='pef_my_reporting_projects_v1';
const REVIEW_VERSION='dart-review-1.5';
const DEFAULT_VIEW='raw';
const isCurrentReview=r=>Boolean(r?.ok&&r.version===REVIEW_VERSION);
const hasChanges=r=>Boolean(isCurrentReview(r)&&r.changes?.length);
const staleNotice='이전 분석 버전의 보관 결과입니다. DART 공시에서 다시 읽은 뒤 사용해주세요.';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const receipt=n=>/^\d{14}$/.test(String(n||''));
const url=n=>receipt(n)?'https://dart.fss.or.kr/dsaf001/main.do?rcpNo='+n:'#';
const date=v=>/^\d{8}$/.test(String(v||''))?`${v.slice(0,4)}.${v.slice(4,6)}.${v.slice(6,8)}`:'일자 미확인';
const correction=x=>/^\s*(?:\[(?:기재정정|첨부정정|정정)\]|기재정정|첨부정정|정정)/.test(x.report_nm||'');
const concern=x=>/철회|중단|취소|회생|부도|연체|횡령|배임|감사의견거절|감사의견부적정/.test(x.report_nm||'');
function base(v){return String(v||'').replace(/^\s*(?:\[(?:기재정정|첨부정정|정정)\]|기재정정|첨부정정|정정)\s*/,'').replace(/\s+/g,' ').trim();}
function buildGroups(items){const m=new Map();for(const x of items||[]){if(!receipt(x.rcept_no))continue;const key=[x.corp_code||x.corp_name,base(x.report_nm),x.flr_nm||x.rcept_no].join('|');if(!m.has(key))m.set(key,[]);if(!m.get(key).some(a=>a.rcept_no===x.rcept_no))m.get(key).push(x);}return [...m.values()].map(rows=>{rows.sort((a,b)=>b.rcept_no.localeCompare(a.rcept_no));return{latest:rows[0],items:rows};});}
function mergeProject(rows,item,review){if(!Array.isArray(rows))throw Error('취재 목록 형식을 확인해야 합니다.');const pid='project-dart-'+item.rcept_no,now=new Date().toISOString(),out=rows.map(p=>({...p}));let p=out.find(p=>p.project_id===pid);
  if(!p){const changes=review?.changes||[],qs=review?.questions||[];p={project_id:pid,clue_id:'dart-'+item.rcept_no,title:item.corp_name+' · '+base(item.report_nm),status:'추가확인',notes:'',judgment:null,judgment_history:[],created_at:now,
    clue:{clue_id:'dart-'+item.rcept_no,detector:'dart_manual_review',fact_status:'단서',headline:item.corp_name+' · '+base(item.report_nm),one_line_signal:changes.length?'정정표에서 변경값을 추출했습니다. 원문 검수와 변경 사유 확인이 필요합니다.':'DART 원문에서 거래 조건과 후속 이행 여부를 확인할 취재입니다.',previous_state:'동일 공시의 정정 전 항목을 기준으로 대조합니다. 서로 다른 거래의 과거 공시를 임의 연결하지 않습니다.',changed_fact:changes.length?changes.slice(0,4).map(d=>`${d.label}: ${d.before} → ${d.after}`).join(' / '):'현재 원문만으로 실질 변경 여부 미확인',confirmed_facts:[],reported:[],unknowns:qs.map(q=>q.still_needed),questions:qs.map(q=>q.question),hypothesis:'공시상 조건 변경이 실제 계약 이행이나 자금조달에 영향을 주었는지 확인한다.',falsification:'기재오류 정정이거나 실제 계약·이행 조건에 변동이 없다면 실질 영향 가설을 재검토한다.',sources:[{source_id:'dart:'+item.rcept_no,label:item.report_nm,url:url(item.rcept_no)}],next_action:'변경 사유와 실제 이행 여부를 공시 담당자·거래상대방에게 확인'}};out.unshift(p);}
  p.dart_review_receipts=[...new Set([...(p.dart_review_receipts||[]),item.rcept_no])];p.updated_at=now;return{rows:out,id:pid};
}
function storyHtml(item,r,selected='all'){
  if(!Topics||!item)return '';
  const lens=Topics.storyContext(item,isCurrentReview(r)?r:null,selected);
  return `<section class="dd-story"><div class="dd-story-top"><b>${esc(lens.topic.label)}</b><small>${esc(lens.basis)}</small></div><p>${esc(lens.why)}</p><div class="dd-story-question"><span>먼저 확인할 질문</span><strong>${esc(lens.question)}</strong></div><p class="dd-story-compare"><b>대조할 자료</b> ${esc(lens.compare)}</p>${lens.evidence_ids.length?`<div class="dd-story-links">${lens.evidence_ids.map((id,i)=>`<a href="#dd-e-${esc(id)}">연결 근거 ${i+1}</a>`).join(' · ')}</div>`:''}<small>취재 방향을 정리한 것입니다. 기사화 판단이나 확인된 인과관계가 아닙니다.</small></section>`;
}
function topicTags(item,r){if(!Topics)return '';return Topics.classify(item,isCurrentReview(r)?r:null).map(t=>`<span class="dd-topic-tag" title="${esc(t.basis_label)}">${esc(t.label)}</span>`).join('');}
function evidenceHtml(r,item,selected='all'){if(!r?.ok)return '<p class="dd-empty">원문을 읽지 못했습니다. 공시 원문에서 확인해주세요.</p>';
  const rows=r.changes||[],fields=r.current_fields||[];
  return `${storyHtml(item,r,selected)}${!isCurrentReview(r)?`<p class="dd-warning" role="status">${staleNotice}</p>`:''}${item?`<details class="dd-details dd-all-evidence"><summary>전체 변경값·원문 근거 ${(r.changes||[]).length}행 보기</summary>`:''}<p class="dd-note">${esc(r.comparison_note)}</p>${rows.length?`<div class="dd-changes">${rows.map(d=>`<article class="dd-change" id="dd-e-${esc(d.evidence_id)}"><b>${esc(d.label)}</b><div class="dd-before-after"><div><small>정정 전</small><span>${esc(d.before)}</span></div><span class="dd-arrow" aria-hidden="true">→</span><div><small>정정 후</small><strong>${esc(d.after)}</strong></div></div>${d.day_delta!==null?`<p class="dd-days">기재된 날짜 기준 ${Math.abs(d.day_delta)}일 ${d.day_delta>0?'뒤로':'앞으로'} 변경 · 실제 이행은 미확인</p>`:''}${d.reason?`<p><small>공시의 정정 사유</small> ${esc(d.reason)}</p>`:''}<a href="${url(r.rcept_no)}" target="_blank" rel="noopener noreferrer">원문 ↗</a><small class="dd-location">${esc(d.source.location)} · 자동 추출, 검수 전</small></article>`).join('')}</div>`:'<p class="dd-empty">비교 가능한 변경값을 추출하지 못했습니다. 변경이 없다는 뜻은 아닙니다.</p>'}
  ${fields.length?`<details class="dd-details"><summary>저장 당시 원문에서 읽은 조건 ${fields.length}개</summary><dl class="dd-fields">${fields.map(f=>`<div id="dd-e-${esc(f.evidence_id)}"><dt>${esc(f.raw_label)}</dt><dd>${esc(f.value)}<small>${esc(f.source.location)}</small></dd></div>`).join('')}</dl></details>`:''}
  ${item?'</details>':''}${item?'<details class="dd-details"><summary>항목별 추가 확인 질문</summary>':'<h4>다음 취재 질문</h4>'}<div class="dd-questions">${(r.questions||[]).map(q=>`<div><b>${esc(q.title)}</b><p>${esc(q.question)}</p><small>${esc(q.still_needed)}</small><div>${q.evidence_ids.map((e,i)=>`<a href="#dd-e-${esc(e)}">근거 ${i+1} 보기</a>`).join(' · ')}</div></div>`).join('')}</div>
  ${item?'</details>':''}${r.warnings?.length?`<details class="dd-details"><summary>자동 추출에서 제외한 항목·한계</summary><p>${r.warnings.map(esc).join('<br>')}</p></details>`:''}`;
}
function brief(item,r){const lens=Topics?.storyContext(item,isCurrentReview(r)?r:null);return[!isCurrentReview(r)?staleNotice:'',item.corp_name+' · '+item.report_nm,url(item.rcept_no),lens?'취재 쟁점: '+lens.topic.label+'\n먼저 확인: '+lens.question+'\n대조할 자료: '+lens.compare:'','DART 원문 자동 추출 · 검수 전',(r?.changes||[]).map(d=>`${d.label}: ${d.before} → ${d.after}\n공시의 정정 사유: ${d.reason||'정정표에서 별도 사유 미확보'}\n${d.source.location}`).join('\n'),...(r?.questions||[]).map(q=>'질문: '+q.question+'\n남은 확인: '+q.still_needed),...(r?.warnings||[])].filter(Boolean).join('\n\n');}
function init(){if(typeof document==='undefined')return;const $=s=>document.querySelector(s),read=(k,def)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v===null?def:v;}catch(_){return def;}};
  document.addEventListener('click',event=>{const a=event.target.closest('a[href^="#dd-e-"]');if(!a)return;const target=document.getElementById(a.hash.slice(1));if(!target)return;event.preventDefault();for(let p=target.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;target.scrollIntoView({block:'center'});});
  function attachProjects(){const rows=read(PROJECTS,[]),reviews=read(STORE,{});if(!Array.isArray(rows))return;
    const targets=[...document.querySelectorAll('.project-card')].map(el=>({el,p:rows.find(p=>p.project_id===el.dataset.id)}));const judge=$('#judgeRoot .judge-panel');if(judge){const pid=new URLSearchParams(location.search).get('project')||localStorage.getItem('pef_selected_project_v1');targets.push({el:judge,p:rows.find(p=>p.project_id===pid)});}
    for(const{el,p}of targets){if(!p?.dart_review_receipts?.length||el.querySelector('.dd-linked'))continue;const d=document.createElement('details');d.className='dd-linked dd-details';d.innerHTML='<summary>DART 변경값·원문·질문 보기</summary><p class="dd-note">공개자료 자동 추출입니다. 기존 취재 메모와 기사화 판단을 바꾸지 않습니다.</p>'+p.dart_review_receipts.filter(n=>reviews[n]?.ok).map(n=>evidenceHtml(reviews[n])).join('');el.append(d);}
  }
  if(!$('#dartDesk')){let scheduled=false;new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;attachProjects();});}).observe(document.body,{childList:true,subtree:true});attachProjects();return;}
  let items=[],groups=[],reviews=read(STORE,{}),days=3,filter='all',group='ALL',query='',view=DEFAULT_VIEW,selectedTopic='all',shown=60,open=new Set(),loading=new Set(),failed=new Map(),sequence=0,controller,batching=false;
  if(!reviews||typeof reviews!=='object'||Array.isArray(reviews))reviews={};
  const message=t=>{$('#deskMessage').textContent=t;};
  const topicCache=new Map();
  function itemTopics(x){const r=reviews[x.rcept_no],old=topicCache.get(x.rcept_no);if(old?.item===x&&old.review===r)return old.topics;const topics=Topics?Topics.classify(x,isCurrentReview(r)?r:null):[];topicCache.set(x.rcept_no,{item:x,review:r,topics});return topics;}
  function matchesItem(x,ignoreTopic=false){const r=reviews[x.rcept_no],q=query.toLowerCase().trim();return(group==='ALL'||x.group_id===group)&&(!q||[x.corp_name,x.flr_nm,x.report_nm].join(' ').toLowerCase().includes(q))&&(ignoreTopic||selectedTopic==='all'||itemTopics(x).some(t=>t.id===selectedTopic))&&(filter==='all'||filter==='correction'&&correction(x)||filter==='concern'&&concern(x)||filter==='changed'&&hasChanges(r)||filter==='unread'&&!isCurrentReview(r)||open.has(x.rcept_no));}
  function visibleGroups(){return groups.map(g=>{const rows=g.items.filter(x=>matchesItem(x));return rows.length?{latest:rows[0],items:rows}:null;}).filter(Boolean);}
  function renderTopics(){const root=$('#reportingTopics');if(!root||!Topics)return;const base=items.filter(x=>matchesItem(x,true)),counts=Object.fromEntries(Topics.TOPICS.map(t=>[t.id,0]));for(const x of base)for(const t of itemTopics(x))counts[t.id]++;root.innerHTML=[{id:'all',label:'전체',count:base.length},...Topics.TOPICS.map(t=>({...t,count:counts[t.id]}))].map(t=>`<button type="button" data-topic="${t.id}" class="${selectedTopic===t.id?'on':''}" aria-pressed="${selectedTopic===t.id}"><span>${esc(t.label)}</span><b>${t.count}</b></button>`).join('');}
  function mini(x){const r=reviews[x.rcept_no],lens=Topics?.storyContext(x,isCurrentReview(r)?r:null,selectedTopic);let out=`<div class="dd-topic-tags">${topicTags(x,r)}</div>`;
    if(lens&&!open.has(x.rcept_no))out+=`<p class="dd-angle">${esc(lens.question)}</p><p class="dd-note">${esc(lens.basis)}</p>`;
    if(r?.ok&&!isCurrentReview(r))return out+'<p class="dd-warning">이전 분석 결과 보관 중 · 새 기준으로 다시 읽어주세요.</p>';
    if(hasChanges(r)){const matching=r.changes.filter(e=>!lens||lens.evidence_ids.includes(e.evidence_id));let chosen=matching.slice(0,2);if(lens?.topic.id==='funding'){const price=matching.find(e=>/발행가|전환가|기준주가/.test(e.label)),shares=matching.find(e=>/신주의종류와수|주식수|주식총수/.test(e.label.replace(/\s/g,'')));if(price&&shares)chosen=[price,shares];}
      if(chosen.length)out+=`<div class="dd-delta-preview">${chosen.map(d=>`<div><b>${esc(d.label)}</b><span>${esc(d.before)} <em>→</em> <strong>${esc(d.after)}</strong></span></div>`).join('')}<small>선택한 쟁점과 연결한 변경값 · 전체 ${r.changes.length}행은 상세에서 확인</small></div>`;else out+='<p class="dd-note">변경값은 있으나 선택한 쟁점과 연결할 항목을 찾지 못했습니다. 상세에서 원문을 확인하세요.</p>';
    }else out+=`<p class="dd-note">${r?.ok?'원문은 읽었지만 비교 가능한 변경값은 미확보입니다.':'원문 미검토 · 공시명으로 취재 쟁점을 분류했습니다.'}</p>`;
    return out;
  }
  function panel(x){const r=reviews[x.rcept_no];return `<section class="dd-review" aria-label="원문 검토 결과">${loading.has(x.rcept_no)?'<p role="status">공시 원문의 정정표와 조건을 읽는 중입니다…</p>':r?.ok?evidenceHtml(r,x,selectedTopic):`<p class="dd-empty">${esc(failed.get(x.rcept_no)||'원문 자동 검토를 시작해주세요.')}</p>`}${failed.has(x.rcept_no)&&r?.ok?`<p class="dd-warning" role="status">다시 읽기 실패: ${esc(failed.get(x.rcept_no))} 기존 보관 결과를 유지합니다.</p>`:''}<div class="dd-review-actions"><button data-read="${x.rcept_no}">다시 읽기</button>${isCurrentReview(r)?`<button data-project="${x.rcept_no}" class="dd-primary">진행중 취재로 보내기 →</button><button data-copy="${x.rcept_no}">질문·근거 복사</button>`:''}</div></section>`;}
  function card(g){const x=g.latest,n=x.rcept_no;return `<article class="dd-card ${hasChanges(reviews[n])?'has-change':''}"><div class="dd-card-head"><span class="dd-category">${esc(x.group_label||'공시')}</span><time>${date(x.rcept_dt)}</time><a href="${url(n)}" target="_blank" rel="noopener noreferrer">DART 원문 ↗</a></div><h3>${esc(x.corp_name)}</h3><div class="dd-report-title">${esc(x.report_nm)}</div><div class="dd-filer">제출자 ${esc(x.flr_nm||'미확인')}</div>${mini(x)}<div class="dd-card-actions"><button class="dd-primary" data-open="${n}" ${loading.has(n)?'disabled':''}>${loading.has(n)?'원문 읽는 중…':open.has(n)?'검토 결과 접기':isCurrentReview(reviews[n])?'변경값·질문 보기':reviews[n]?.ok?'새 기준으로 다시 읽기':'원문·변경내용 읽기'}</button>${g.items.length>1?`<details class="dd-siblings" ${g.items.slice(1).some(a=>open.has(a.rcept_no))?'open':''}><summary>같은 공시명 ${g.items.length}건</summary><p>회사·공시명·제출자 기준 검색 묶음입니다. 동일 거래로 확인한 이력이 아닙니다.</p>${g.items.map(a=>`<div><a href="${url(a.rcept_no)}" target="_blank" rel="noopener noreferrer">${date(a.rcept_dt)} · ${esc(a.report_nm)}</a><button data-read="${a.rcept_no}">이 원문 읽기</button>${a.rcept_no!==n&&open.has(a.rcept_no)?panel(a):''}</div>`).join('')}</details>`:''}</div>${open.has(n)?panel(x):''}</article>`;}
  function render(){const list=visibleGroups().sort((a,b)=>b.latest.rcept_no.localeCompare(a.latest.rcept_no));$('#dartCards').innerHTML=list.length?list.slice(0,shown).map(card).join(''):'<p class="dd-empty">조건에 맞는 공시가 없습니다. 다른 쟁점이나 조회 기간을 선택해주세요.</p>';$('#more').hidden=list.length<=shown;
    $('#sReview').textContent=items.filter(x=>isCurrentReview(reviews[x.rcept_no])).length;$('#sDiff').textContent=items.filter(x=>hasChanges(reviews[x.rcept_no])).length;$('#sTotal').textContent=items.length;
    $('#deskCount').textContent=`${list.length}개 공시명 묶음 · 최신순 · 기사 순위가 아닙니다`;
    const raw=items.filter(x=>matchesItem(x)).sort((a,b)=>b.rcept_no.localeCompare(a.rcept_no));$('#rawRows').innerHTML=raw.length?raw.map(x=>`<tr><td>${date(x.rcept_dt)}</td><td>${esc(x.corp_name)}</td><td><a href="${url(x.rcept_no)}" target="_blank" rel="noopener noreferrer">${esc(x.report_nm)}</a></td><td class="dd-raw-topics">${topicTags(x,reviews[x.rcept_no])}</td><td>${esc(x.flr_nm)}</td><td><button data-read="${x.rcept_no}" aria-label="${esc(x.corp_name)} 변화·질문">변화·질문</button></td></tr>`).join(''):'<tr><td colspan="6">조건에 맞는 공시가 없습니다. 쟁점·분야·조회 기간을 확인해주세요.</td></tr>';
    if($('#rawCount'))$('#rawCount').textContent=`${raw.length}건 · 최신 공시순`;
    $('#deskView').hidden=view!=='desk';$('#rawView').hidden=view!=='raw';$('#batch').hidden=view!=='desk';document.querySelectorAll('[data-desk-only]').forEach(el=>el.hidden=view!=='desk');
    document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('on',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('on',b.dataset.filter===filter);b.setAttribute('aria-pressed',String(b.dataset.filter===filter));});renderTopics();
  }
  async function readReceipt(n,{expand=true}={}){if(!receipt(n)||loading.has(n))return false;loading.add(n);if(expand)open.add(n);failed.delete(n);render();
    try{const r=await fetch('/api/dart-feed?action=review&rcept_no='+n,{cache:'no-store',signal:AbortSignal.timeout(25000)}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'원문 읽기 실패');if(d.rcept_no!==n||!isCurrentReview(d))throw Error('분석 버전이나 접수번호가 일치하지 않습니다. 화면을 새로고침한 뒤 다시 읽어주세요.');reviews[n]=d;try{localStorage.setItem(STORE,JSON.stringify(reviews));}catch(_){message('브라우저 저장공간이 부족합니다. 이번 결과를 복사해 보관해주세요. 기존 기록은 지우지 않았습니다.');}}
    catch(e){failed.set(n,e.name==='TimeoutError'?'원문 응답이 늦습니다. 원문 링크에서 확인하거나 다시 읽기를 눌러주세요.':e.message);}finally{loading.delete(n);render();}return !failed.has(n)&&isCurrentReview(reviews[n]);
  }
  async function batch(){if(batching||view!=='desk')return;batching=true;$('#batch').disabled=true;let success=0,attempted=0;
    const list=visibleGroups().map(g=>g.latest).filter(x=>correction(x)&&!isCurrentReview(reviews[x.rcept_no])&&!failed.has(x.rcept_no)).slice(0,3);
    try{if(!list.length)message('현재 목록에서 새로 읽을 정정공시가 없습니다. 개별 공시의 다시 읽기를 이용하세요.');for(const x of list){if(view!=='desk')break;message(`정정공시 원문 ${attempted+1}/${list.length}건 확인 중…`);attempted++;if(await readReceipt(x.rcept_no,{expand:false}))success++;}if(attempted)message(`원문 조회 ${attempted}건 중 ${success}건 성공${attempted-success?' · '+(attempted-success)+'건 미확보':''}. 자동 추출값은 원문과 대조해주세요.`);}finally{batching=false;$('#batch').disabled=false;}
  }
  async function load(fresh=false){controller?.abort();controller=new AbortController();const token=++sequence;$('#refresh').disabled=true;$('#status').textContent='DART 확인 중…';
    try{const r=await fetch(`/api/dart-feed?days=${days}&limit=700${fresh?'&fresh=1':''}&_=${Date.now()}`,{signal:controller.signal,cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'조회 실패');if(token!==sequence)return;items=d.items||[];groups=buildGroups(items);shown=60;const cov=d.coverage||{};$('#coverage').textContent=`${d.range?.bgn||''}~${d.range?.end||''} · 수집 ${d.scanned||0}건 중 관련 공시 ${d.matched??items.length}건${cov.complete===false?' · 일부 페이지 미수집':''}${cov.display_limited?' · 표시 한도 적용':''} · 조회 ${new Date(d.fetched_at||Date.now()).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul'})}`;$('#coverage').classList.toggle('dd-warning',cov.complete===false);$('#status').textContent=`${days}일 · 관련 공시 ${items.length}건`;render();}
    catch(e){if(token!==sequence||e.name==='AbortError')return;message('조회 실패: '+e.message+(items.length?' 이전 목록을 유지합니다.':''));$('#status').textContent='조회 실패';}finally{if(token===sequence)$('#refresh').disabled=false;}
  }
  $('#refresh').onclick=()=>load(true);$('#batch').onclick=batch;$('#more').onclick=()=>{shown+=60;render();};$('#search').oninput=e=>{query=e.target.value;shown=60;render();};$('#groups').onchange=e=>{group=e.target.value;render();};
  document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.days){days=Number(b.dataset.days);document.querySelectorAll('[data-days]').forEach(x=>x.classList.toggle('on',x===b));load(true);}
    if(b.dataset.filter){filter=b.dataset.filter;shown=60;render();}if(b.dataset.view){view=b.dataset.view==='desk'?'desk':DEFAULT_VIEW;render();}if(b.dataset.topic){selectedTopic=b.dataset.topic;shown=60;render();}
    const n=b.dataset.open||b.dataset.read;if(n){if(b.dataset.open&&open.has(n)){open.delete(n);render();}else if(isCurrentReview(reviews[n])&&!b.dataset.read){open.add(n);render();}else{view='desk';await readReceipt(n);}}
    if(b.dataset.project){const n=b.dataset.project,x=items.find(x=>x.rcept_no===n);if(!x||!isCurrentReview(reviews[n]))return;try{const result=mergeProject(read(PROJECTS,[]),x,reviews[n]);localStorage.setItem(PROJECTS,JSON.stringify(result.rows));location.href='/projects.html?project='+encodeURIComponent(result.id);}catch(err){message('저장하지 못했습니다: '+err.message);}}
    if(b.dataset.copy){const n=b.dataset.copy,x=items.find(x=>x.rcept_no===n);if(!x||!isCurrentReview(reviews[n]))return;const content=brief(x,reviews[n]);try{await navigator.clipboard.writeText(content);message('질문·변경값·출처를 복사했습니다.');}catch(_){const t=document.createElement('textarea');t.className='dd-copy';t.value=content;t.readOnly=true;b.parentElement.append(t);t.focus();t.select();}}
  });render();load();
}
return{DEFAULT_VIEW,storyHtml,topicTags,REVIEW_VERSION,isCurrentReview,hasChanges,buildGroups,mergeProject,correction,concern,base,evidenceHtml,brief,init};
});
