const test=require('node:test'),assert=require('node:assert/strict'),C=require('../news-reader-core'),Client=require('../news-reader-account-client');
const id='11111111-1111-4111-8111-111111111111',user={id,email:'a@example.invalid'},key='https://example.invalid/a';
function store(){const map=new Map();return {map,reads:0,writes:0,getItem(k){this.reads++;return this.map.get(k)||null;},setItem(k,v){this.writes++;this.map.set(k,v);}};}
function setup({signedin=true,initial=[],failSave=false}={}){
 const storage=store(),calls=[],rows=new Map(initial.map(x=>[x.kind+'|'+x.key,x]));let authenticated=signedin;
 const fetcher=async(url,opt)=>{calls.push({url,opt});const p=new URL(url,'https://example.invalid'),action=p.searchParams.get('reader'),body=opt.body?JSON.parse(opt.body):null;let status=200,data;
 if(action==='status')data={ok:true,ready:true,user:authenticated?user:null};
 else if(action==='logout'){authenticated=false;data={ok:true};}
 else if(action==='records'&&opt.method==='GET')data={ok:true,records:[...rows.values()],next:null};
 else if(action==='records'){if(failSave){status=409;data={ok:false,error:'version conflict'};}else{const out=body.changes.map(c=>({...c,version:c.expected_version+1}));out.forEach(c=>rows.set(c.kind+'|'+c.key,c));data={ok:true,records:out};}}
 else if(action==='send-code')data={ok:true};
 else if(action==='verify-code'){authenticated=true;data={ok:true,user};}
 else throw Error('unexpected request');
 return {ok:status===200,status,json:async()=>data};};
 const client=Client.create({core:C,fetcher,storage});return {client,storage,calls,rows};
}
const change={kind:'bookmark',key,value:{article:{title:'test article',source_url:key}}};
test('signed-out start does not read or upload guest records',async()=>{const s=setup({signedin:false});await s.client.sync();assert.equal(s.client.state().mode,'signedout');assert.equal(s.storage.reads,0);assert.equal(s.calls.length,1);});
test('account save never touches localStorage',async()=>{const s=setup();await s.client.sync();await s.client.save([change]);assert.equal(s.storage.writes,0);assert.equal(s.client.state().records.bookmark[key].article.title,'test article');});
test('requests carry cookies only through same-origin credentials',async()=>{const s=setup();await s.client.sync();await s.client.save([change]);for(const c of s.calls){assert.equal(c.opt.credentials,'same-origin');assert.equal(c.opt.cache,'no-store');assert.equal(c.opt.headers.Authorization,undefined);}});
test('writes carry the verified account and observed version',async()=>{const s=setup({initial:[{...change,version:4}]});await s.client.sync();await s.client.save([{...change,value:null}]);const c=s.calls.at(-1);assert.equal(c.opt.headers['X-Reader-User'],id);assert.equal(JSON.parse(c.opt.body).changes[0].expected_version,4);});
test('logout empties account memory but preserves original guest data',async()=>{const s=setup({initial:[{...change,version:1}]});s.storage.map.set('ib-news-desk-v1','{"saved":{}}');await s.client.sync();await s.client.logout();assert.equal(s.client.state().user,null);assert.equal(Object.keys(s.client.state().records.bookmark).length,0);assert.equal(s.storage.map.get('ib-news-desk-v1'),'{"saved":{}}');assert.equal(s.storage.writes,0);});
test('account save failure clears memory, never falls back to browser writes',async()=>{const s=setup({failSave:true,initial:[{...change,version:1}]});await s.client.sync();await assert.rejects(s.client.save([change]),/conflict/);assert.equal(s.client.state().mode,'blocked');assert.equal(s.storage.writes,0);assert.equal(Object.keys(s.client.state().records.bookmark).length,0);});
test('guest storage requires explicit selection',async()=>{const s=setup({signedin:false});await s.client.sync();await assert.rejects(s.client.save([change]),/로그인/);await s.client.useGuest();await s.client.save([change]);assert.equal(s.storage.writes,1);assert.equal(s.client.state().mode,'guest');assert.ok(!s.calls.some(c=>c.url.includes('reader=records')));});
test('explicit import preserves original local records and does not resurrect cloud tombstones',async()=>{const s=setup({initial:[{...change,value:null,version:3}]});const g=C.apply(C.empty(),[change,{...change,key:'https://example.invalid/b'}]);s.storage.map.set('ib-news-reader-v2',JSON.stringify(g));await s.client.sync();assert.equal(s.storage.reads,0);const n=await s.client.importGuest();assert.equal(n,1);assert.equal(s.storage.writes,0);assert.equal(s.client.state().records.bookmark[key],undefined);assert.ok(s.storage.map.get('ib-news-reader-v2').includes(key));});
test('invalidating session removes private records immediately',async()=>{const s=setup({initial:[{...change,version:1}]});await s.client.sync();s.client.invalidate();assert.equal(s.client.state().mode,'checking');assert.equal(s.client.state().user,null);assert.equal(Object.keys(s.client.state().records.bookmark).length,0);});
test('late account response after invalidation is discarded',async()=>{let release;let calls=0;const client=Client.create({core:C,storage:store(),fetcher:async()=>{calls++;if(calls===1)return {ok:true,json:async()=>({ok:true,ready:true,user})};await new Promise(r=>{release=r;});return {ok:true,json:async()=>({ok:true,records:[{...change,version:1}],next:null})};}});const pending=client.sync();while(!release)await new Promise(r=>setImmediate(r));client.invalidate();release();await pending;assert.equal(client.state().user,null);assert.equal(Object.keys(client.state().records.bookmark).length,0);});
test('unavailable localStorage does not break account-only mode',async()=>{const client=Client.create({core:C,storage:null,fetcher:async()=>({ok:true,json:async()=>({ok:true,ready:true,user:null})})});await client.sync();assert.equal(client.state().mode,'signedout');assert.equal(client.guestCount(),null);});
