const test=require('node:test'),assert=require('node:assert/strict'),C=require('../news-reader-core');
const input=(title,id=1)=>({title,source_url:'https://example.com/news/'+id,published_at:'2026-09-08T03:00:00Z',source_name:'검증용 매체'});
const relevant=['국민연금 출자사업 운용사 선정','한국벤처투자 출자 기준 변경','A캐피탈 3호 펀드 결성기한 연장','교직원공제회 첫 해외거점 사무소 개소','국민연금 운용인력 금융권 이동','보험사 악사손보 인수 자문사 선정','PEF 기업 매각 본입찰','스타트업 시리즈 A 투자 유치','기업 회사채 차환','펀드 결성 무산','국민연금 환헤지 중단','국민연금 투자 운용사 가점 논란','PEF 업계 동향','인수금융 리파이낸싱','채용 플랫폼 기업 경영권 인수'];
const excluded=['국민연금 기초연금 신청 안내','국민연금 외국인 가입 추납 제한','국민연금 치매 재산관리 신청','공제회 병원 복지 확대 협약','공제회 교직원 복지 협약','인수파출소 어르신 보이스피싱 예방','삼성생명 예상인수결과 제공시스템 보험가입 확인','지방계약 워크숍 개최','국민연금 수해복구 봉사활동','LP 음반 레코드판 출시','수학 인수분해 교육','오늘의 종목 주식 추천'];
for(const title of relevant)test('관련 기사 유지: '+title,()=>assert.equal(C.assess(input(title)).status,'relevant'));
for(const title of excluded)test('기본 목록에서 분리: '+title,()=>assert.equal(C.assess(input(title)).status,'excluded'));
test('기관명만 있으면 검토',()=>assert.equal(C.assess(input('국민연금 행사 소식')).status,'review'));
test('default excludes noise but all and review preserve it',()=>{const rows=[input(relevant[0],1),input(excluded[0],2)];assert.equal(C.select(rows,C.empty()).length,1);assert.equal(C.select(rows,C.empty(),{view:'all'}).length,2);assert.equal(C.select(rows,C.empty(),{view:'review'}).length,1);});
test('explicit read does not mark unseen items',()=>{const a=input(relevant[0],1),b=input(relevant[0],2);const next=C.apply(C.empty(),[{kind:'read',key:C.key(a),value:{revision:C.revision(a)}}]);assert.equal(C.unread(a,next),false);assert.equal(C.unread(b,next),true);assert.equal(C.select([a,b],next).length,1);});
test('opening source is not proof of reading',()=>{const a=input(relevant[0]);assert.equal(C.unread(a,C.apply(C.empty(),[{kind:'opened',key:C.key(a),value:{}}])),true);});
test('changed headline returns to unread without claiming fact change',()=>{const a=input(relevant[0]),next=C.apply(C.empty(),[{kind:'read',key:C.key(a),value:{revision:C.revision(a)}}]);assert.equal(C.unread({...a,title:a.title+' 정정'},next),true);});
test('bookmarks outlive collection window',()=>{const a=input(relevant[0]),next=C.apply(C.empty(),[{kind:'bookmark',key:C.key(a),value:{article:a}}]);assert.equal(C.select([],next,{view:'saved'})[0].title,a.title);});
test('hide and undo do not destroy source',()=>{const a=input(relevant[0]),before=JSON.stringify(a),hidden=C.apply(C.empty(),[{kind:'hidden',key:C.key(a),value:{article:a}}]);assert.equal(C.select([a],hidden).length,0);assert.equal(C.select([],hidden,{view:'hidden'}).length,1);const restored=C.apply(hidden,[{kind:'hidden',key:C.key(a),value:null}]);assert.equal(C.select([a],restored).length,1);assert.equal(JSON.stringify(a),before);});
test('watch requires all words',()=>{assert.equal(C.watchMatches(input('A캐피탈 3호 펀드 결성'),{query:'A캐피탈 3호'}),true);assert.equal(C.watchMatches(input('A캐피탈 4호 펀드 결성'),{query:'A캐피탈 3호'}),false);});
test('3호 is not 13호',()=>assert.equal(C.watchMatches(input('A캐피탈 13호 펀드 결성'),{query:'A캐피탈 3호'}),false));
test('canonical entity watch uses ID not partial names',()=>assert.equal(C.watchMatches({...input('펀드 결성'),related_entities:[{entity_key:'vc:a'}]},{entity_key:'vc:b'}),false));
test('new reporting is unread even under same watch',()=>{const a=input('A캐피탈 3호 펀드 결성',1),b=input('A캐피탈 3호 펀드 연장',2);const state=C.apply(C.empty(),[{kind:'read',key:C.key(a),value:{revision:C.revision(a)}},{kind:'watch',key:'q:A캐피탈 3호',value:{query:'A캐피탈 3호'}}]);assert.equal(C.select([a,b],state,{view:'tracked'}).length,2);assert.equal(C.unread(b,state),true);});
test('legacy records preserved without mutating source',()=>{const old={saved:{'https://example.com/a':1788800000000},overrides:{'https://example.com/a':'deal'}},before=JSON.stringify(old);assert.equal(Object.keys(C.legacy(old).bookmark).length,1);assert.equal(JSON.stringify(old),before);});
test('malformed legacy timestamp does not erase valid links',()=>assert.equal(Object.keys(C.legacy({saved:{'https://example.com/a':'bad'}}).bookmark).length,1));
test('no executable or credential URLs accepted',()=>{assert.equal(C.url('javascript:alert(1)'), '');assert.equal(C.url('https://name:secret@example.com/'),'');});
test('private state does not accept notes or arbitrary fields',()=>{const v=C.validate({kind:'bookmark',key:'https://example.com/a',value:{notes:'secret',article:{title:'test',source_url:'https://example.com/a',phone:'private'}}});assert.equal(JSON.stringify(v).includes('private'),false);assert.equal(JSON.stringify(v).includes('secret'),false);});
test('prototype property cannot modify state prototype',()=>{const s=C.apply(C.empty(),[{kind:'watch',key:'__proto__',value:{query:'fund'}}]);assert.equal(Object.getPrototypeOf(s.watch),null);assert.equal(Object.prototype.query,undefined);});
test('independent reader states never share changes',()=>{const a=input(relevant[0]),one=C.apply(C.empty(),[{kind:'bookmark',key:C.key(a),value:{article:a}}]),two=C.empty();assert.equal(C.select([],one,{view:'saved'}).length,1);assert.equal(C.select([],two,{view:'saved'}).length,0);});
test('exclusive filter uses editorial markers and remains domestic-only',()=>{
 const fixtures=[['[단독] A사 매각 추진',true],['【단독】 A사 인수',true],['단독: A사 투자 유치',true],['A사 단독 입찰',false],['단독주택 투자 확대',false],['A사 단독 대표 선임',false]];
 for(const [title,expected] of fixtures)assert.equal(C.exclusive({title}),expected,title);
 assert.equal(C.exclusive({title:'[단독] CVC 매각 검토',news_scope:'foreign'}),false);
});
test('exclusive and subject filters compose across live and saved articles',()=>{
 const T=require('../news-taxonomy'),item={title:'[단독] PEF 인수금융 확보하고 A사 매각 추진',source_url:'https://example.com/exclusive',published_at:new Date().toISOString()};
 const ordinary={...item,title:'PEF 인수금융 확보',source_url:'https://example.com/ordinary'};
 let state=C.apply(C.empty(),[{kind:'bookmark',key:item.source_url,value:{article:item}}]);
 const options={view:'all',newsScope:'domestic',exclusiveOnly:true,category:'deal',classify:T.classify};
 assert.deepEqual(C.select([item,ordinary],state,options).map(C.key),[item.source_url]);
 assert.equal(C.select([],state,{...options,view:'saved'}).length,1);
 state=C.apply(state,[{kind:'hidden',key:item.source_url,value:{article:item}}]);
 assert.equal(C.select([item],state,options).length,0);
});
test('secondary subject is selectable but a personal classification remains authoritative',()=>{
 const T=require('../news-taxonomy'),item={title:'PEF 인수금융 확보하고 A사 매각 추진',source_url:'https://example.com/multiple'};
 const options={view:'all',category:'deal',classify:T.classify};
 assert.equal(T.classify(item).category_id,'credit');
 assert.equal(C.select([item],C.empty(),options).length,1);
 const state=C.apply(C.empty(),[{kind:'override',key:item.source_url,value:{category:'people'}}]);
 assert.equal(C.select([item],state,options).length,0);
 assert.equal(C.select([item],state,{...options,category:'people'}).length,1);
});
