const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Module=require('node:module'),path=require('node:path');
const I=require('../scripts/integrate-auth-link');
const filename=path.resolve('lib/news-reader-account.js'),source=I.account(fs.readFileSync(filename,'utf8'));
const mod=new Module(filename,module);mod.filename=filename;mod.paths=Module._nodeModulePaths(path.dirname(filename));mod._compile(source,filename);const A=mod.exports;
const env={SUPABASE_URL:'https://fixture-project.supabase.co',SUPABASE_SECRET_KEY:'fixture-server-secret',SUPABASE_PUBLISHABLE_KEY:'fixture-public-key'};
const user={id:'11111111-1111-4111-8111-111111111111',email:'tester@example.invalid',role:'authenticated',email_confirmed_at:'2026-09-08',is_anonymous:false};
const base={host:'ainobi.news',origin:'https://ainobi.news','x-news-reader':'1','content-type':'application/json'};
function res(){return{headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},getHeader(k){return this.headers[k.toLowerCase()];},removeHeader(k){delete this.headers[k.toLowerCase()];},status(code){this.code=code;return this;},json(body){this.body=body;return this;}};}
function harness(){const calls=[];const handler=A.createHandler({env,fetcher:async(url,options)=>{calls.push({url,options});const p=new URL(url).pathname;let data=true;if(p==='/auth/v1/otp')data={};else if(p==='/auth/v1/token'||p==='/auth/v1/verify')data={access_token:'fixture-access',refresh_token:'fixture-refresh',expires_in:3600};else if(p==='/auth/v1/user')data=user;return{ok:true,status:200,json:async()=>data};}});return{calls,async run(action,body,headers={},method='POST'){const r=res();await handler({query:{reader:action},method,headers:{...base,...headers},body},r);return r;}};}
test('actual account transform is idempotent and compiles',()=>{assert.equal(I.account(source),source);assert.doesNotThrow(()=>new vm.Script(source));});
test('actual send uses correct redirect query and PKCE, with only pending cookie sent to client',async()=>{const h=harness(),r=await h.run('send-code',{email:user.email});assert.equal(r.code,200);const call=h.calls.find(x=>new URL(x.url).pathname==='/auth/v1/otp');assert.equal(new URL(call.url).searchParams.get('redirect_to'),'https://ainobi.news/auth/callback.html');const payload=JSON.parse(call.options.body);assert.equal(payload.code_challenge_method,'s256');assert.match(payload.code_challenge,/^[\w-]{43}$/);assert.equal(payload.code_verifier,undefined);assert.equal(r.headers['set-cookie'].length,1);assert.ok(!JSON.stringify(r.body).includes(payload.code_challenge));});
test('actual clicked-link route verifies and sets existing secure cookie session',async()=>{const h=harness(),r=await h.run('send-code',{email:user.email});const cookie=r.headers['set-cookie'][0].split(';')[0];const done=await h.run('finish-link',{code:'a'.repeat(32)},{cookie});assert.equal(done.code,200);assert.equal(done.body.user.id,user.id);assert.match(done.headers['cache-control'],/no-store/);assert.ok(done.headers['set-cookie'].every(x=>/Secure; HttpOnly; SameSite=Strict/.test(x)));assert.ok(!JSON.stringify(done.body).includes('fixture-access'));});
test('new route cannot be called via GET or another site',async()=>{for(const [headers,method,status]of [[{},'GET',405],[{origin:'https://evil.invalid'},'POST',403],[{'x-news-reader':undefined},'POST',403]]){const h=harness(),r=await h.run('finish-link',{code:'a'.repeat(32)},headers,method);assert.equal(r.code,status);assert.equal(h.calls.length,0);}});
test('no pending cookie means no PKCE exchange',async()=>{const h=harness(),r=await h.run('finish-link',{code:'a'.repeat(32)});assert.equal(r.code,401);assert.ok(!h.calls.some(x=>x.url.includes('grant_type=pkce')));});
test('existing numeric OTP still works after a PKCE-bound request',async()=>{const h=harness(),sent=await h.run('send-code',{email:user.email});const r=await h.run('verify-code',{email:user.email,code:'123456'},{cookie:sent.headers['set-cookie'][0].split(';')[0]});assert.equal(r.code,200);assert.ok(h.calls.some(x=>new URL(x.url).pathname==='/auth/v1/verify'));});
