const test=require('node:test'),assert=require('node:assert/strict');
const N=require('../lib/news-translation'),C=require('../news-reader-core');
const item={title:'CVC explores $2 billion sale',source_url:'https://example.com/title',news_scope:'foreign',snippet:''};
const env={OPENAI_API_KEY:'test-not-a-secret',SUPABASE_URL:'https://example.test',SUPABASE_SECRET_KEY:'test-service'};
function storage(){const rows=new Map();return {rows,read:async ids=>ids.map(id=>rows.get(id)).filter(Boolean),claim:async xs=>xs.filter(x=>!rows.has(x.id)).map(x=>{const row={...x,status:'pending',updated_at:new Date().toISOString()};rows.set(x.id,row);return row;}),reclaim:async()=>[],save:async xs=>xs.forEach(x=>rows.set(x.id,x))};}
function provider(requests){return async(url,options)=>{requests.push({url,options});const inputs=JSON.parse(JSON.parse(options.body).input);return {ok:true,json:async()=>({id:'resp_test',status:'completed',usage:{input_tokens:123,output_tokens:22},output:[{content:[{type:'output_text',text:JSON.stringify({translations:inputs.map(x=>({id:x.id,title_ko:'CVC, 20억 달러 규모 매각 검토',snippet_ko:''}))})}]}]})};};}
test('translation is saved before reuse and never changes reading revision or original',async()=>{const db=storage(),requests=[];const first=await N.translateItems([item],{env,storage:db,fetcher:provider(requests)});assert.equal(first.items[0].title,item.title);assert.equal(first.status.translated,1);assert.equal(C.revision(first.items[0]),C.revision(item));assert.equal(db.rows.get(N.record(item).id).status,'ready');const second=await N.translateItems([item],{env,storage:db,fetcher:provider(requests)});assert.equal(second.items[0].title_ko,first.items[0].title_ko);assert.equal(requests.length,1);assert.ok(!requests[0].options.body.includes(item.source_url));});
test('Korean snapshots remain searchable after the live feed no longer contains the item',()=>{const translated={...item,title_ko:'CVC, 20억 달러 규모 매각 검토'};const state=C.apply(C.empty(),[{kind:'bookmark',key:item.source_url,value:{article:translated}}]);assert.equal(C.select([],state,{view:'saved',newsScope:'foreign',query:'매각'}).length,1);assert.equal(C.select([],state,{view:'saved',newsScope:'foreign',query:'explores'}).length,1);});
test('missing API key still serves already stored translations without generation',async()=>{const db=storage(),row=N.record(item);db.rows.set(row.id,{...row,status:'ready',title_ko:'CVC 매각 검토'});const x=await N.translateItems([item],{env:{...env,OPENAI_API_KEY:''},storage:db,fetcher:()=>{throw Error('no call');}});assert.equal(x.status.translated,1);});
test('failed translations are disclosed; original article is retained',async()=>{const db=storage();const x=await N.translateItems([item],{env,storage:db,fetcher:async()=>({ok:false,status:429})});assert.equal(x.items[0].title,item.title);assert.equal(x.status.failed,1);assert.equal(x.status.error,'translation_quota_or_rate_limit');assert.equal(db.rows.get(N.record(item).id).status,'failed');});
test('unmatched output IDs cannot attach a translation to the wrong article',async()=>{const row=N.record(item);await assert.rejects(N.generate([row],{key:'test',fetcher:async()=>({ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({translations:[{id:'wrong',title_ko:'다른 기사',snippet_ko:''}]})}]}]})})}),/invalid_response/);});
