const test=require('node:test');const assert=require('node:assert/strict');const C=require('../lib/reporting-calendar');
const reference='2026-09-11T00:00:00Z';
test('Korean date crosses UTC midnight correctly',()=>assert.equal(C.kstDay(Date.parse('2026-09-10T15:01:00Z')),'2026-09-11'));
test('invalid dates rejected instead of rolling over',()=>{assert.equal(C.validDate(2026,2,30),null);assert.equal(C.validDate(2026,9,18),'2026-09-18');});
test('publication and registration deadlines do not become an event date',()=>{assert.equal(C.eventDate('게시일 2026-09-11\n신청기간: 9월 14일까지\n벤처투자 포럼 안내',reference),null);assert.equal(C.eventDate('9월 10일에 따르면 포럼을 개최할 계획이다.',reference),null);});
test('explicit event date outranks registration deadline',()=>{const e=C.makeEvent({title:'벤처투자 포럼 안내',url:'https://www.kvca.or.kr/test',published_at:reference},'신청기간: 9월 14일까지\n일시: 2026년 9월 18일 09:30~12:00\n장소: 콘래드호텔\n주최: 자본시장연구원');assert.equal(e.date,'2026-09-18');assert.equal(e.time,'09:30–12:00');assert.equal(e.venue,'콘래드호텔');});
test('LP selections and training are excluded',()=>{for(const title of ['출자사업 선정결과 설명회','벤처투자 양성과정 세미나'])assert.equal(C.makeEvent({title,url:'https://test/'},'일시:2026년9월18일'),null);});
test('FSC rows retain relevant briefing and exclude general meetings',()=>{const html='<table><tr><td>1</td><td>2026-09-18</td><td>10:00 ~</td><td>자본시장 제도개선 브리핑 (정부서울청사)</td></tr><tr><td>2</td><td>2026-09-18</td><td>09:00 ~</td><td>주간업무회의 (정부서울청사)</td></tr></table>';const out=C.parseFsc(html,{id:'fsc-chair',name:'금융위원장 일정',url:'https://www.fsc.go.kr/fsc020301'});assert.equal(out.length,1);assert.equal(out[0].kind,'announcement');assert.equal(out[0].venue,'정부서울청사');});
test('missing FSC table is failure, not a successful empty schedule',()=>assert.throws(()=>C.parseFsc('<html>접근 불가</html>',{}),/FORMAT/));
test('weekly policy announcement has schedule date, not article date',()=>{const out=C.parseWeekly('◇9월 14일(월)\n▲자본시장 공시제도 개선방안 발표(12:00)\n▲보험 소비자 민원 통계 발표\n◇9월 15일(화)\n▲벤처투자 간담회(10:00)',{url:'https://news.test/article',published_at:reference});assert.equal(out.length,2);assert.equal(out[0].date,'2026-09-14');assert.equal(out[1].kind,'event');});
test('failed source retains last known events; explicit changes have history',()=>{const now=Date.parse(reference),old={id:'a',title:'자본시장 포럼',date:'2026-09-18',time:'10:00',venue:'서울',status:'scheduled'};assert.equal(C.mergeEvents([old],[],now).length,1);const next=C.mergeEvents([old],[{...old,date:'2026-09-19',status:'postponed'}],now)[0];assert.equal(next.previous_date,'2026-09-18');assert.equal(next.changed_at,reference.replace('Z','.000Z'));});
test('past events are never moved into the upcoming date window',()=>{const now=Date.parse(reference),old={id:'a',title:'KB 코리아 컨퍼런스',date:'2026-09-10',time:'08:00'};assert.equal(C.mergeEvents([old],[],now)[0].date,'2026-09-10');});
test('official event title supplies date when the notice body is a poster',()=>{const e=C.makeEvent({title:'「아시아창업엑스포 FLY ASIA2026」 개최 안내(10/7~8, 부산)',url:'https://www.kvca.or.kr/event',source_id:'kvca',published_at:reference},'행사 포스터');assert.equal(e.date,'2026-10-07');assert.equal(e.evidence,'「아시아창업엑스포 FLY ASIA2026」 개최 안내(10/7~8, 부산)');});

test('official seminar programme accepts its theme as title',()=>{const e=C.makeEvent({title:'혁신과 성장을 견인하는 자본시장 – 생산적 금융 전환 과제',url:'https://www.kcmi.re.kr/seminar/seminar_program?eno=317',source_id:'kcmi'},'일시 :2026년 09월 18일 (금), 09:30~12:00\n주최 :자본시장연구원');assert.equal(e.date,'2026-09-18');});

test('multi-day conferences retain their final day',()=>{assert.equal(C.endDate('10/7~8, 부산','2026-10-07'),'2026-10-08');assert.equal(C.endDate('9월 29일(화) ~ 30일(수)','2026-09-29'),'2026-09-30');});

test('seminar date metadata outside the programme body is retained',()=>{const html='<main><h2>혁신과 성장을 견인하는 자본시장</h2><ul><li>일시 :2026년 09월 18일 (금), 09:30~12:00</li></ul><div class="view_content">주제발표와 토론 프로그램</div></main>';const e=C.makeEvent({title:'혁신과 성장을 견인하는 자본시장',url:'https://www.kcmi.re.kr/seminar/seminar_program?eno=317',source_id:'kcmi'},C.pageText(html));assert.equal(e.date,'2026-09-18');});
